 google_site_verification:  google-site-verification=GnPKZvfH5PriOCkiK_v32CA2WOJNxKr9_JA9baCasnQ 
 bing_site_verification:  # out your bing-site-verification ID (Bing Webmaster) 
 enable_google_verification: true  # enables google site verification 